name: sequana_chipseq
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- samtools>1.7
- bamtools
- bedtools
- bowtie2>=2.3
- fastqc
- subread
- fastp
- deeptools
- picard>2.20
- ucsc-bedgraphtobigwig
- homer
- macs3
- multiqc
- graphviz
- snakemake-minimal
- pulp>=2.8
- pip:
  - sequana>=0.21.0
  - sequana_pipetools>=1.5.3
  - sequana-wrappers>=26.4.1
